---
title: "Data types"
description: >
  Learn about fundamental data types in Apache Arrow and how those 
  types are mapped onto corresponding data types in R 
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data types}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Arrow has a rich data type system that includes direct parallels with R's data types and much more.

In the tables, entries with a `-` are not currently implemented.

## R to Arrow

| R type                   | Arrow type |
|--------------------------|------------|
| logical                  | boolean    |
| integer                  | int32      |
| double ("numeric")       | float64^1^ |
| character                | utf8^2^    |
| factor                   | dictionary |
| raw                      | uint8      |
| Date                     | date32     |
| POSIXct                  | timestamp  |
| POSIXlt                  | struct     |
| data.frame               | struct     |
| list^3^                  | list       |
| bit64::integer64         | int64      |
| hms::hms                 | time32     |
| difftime                 | duration   |
| vctrs::vctrs_unspecified | null       |



^1^: `float64` and `double` are the same concept and data type in Arrow C++; 
however, only `float64()` is used in arrow as the function `double()` already 
exists in base R

^2^: If the character vector exceeds 2GB of strings, it will be converted to a 
`large_utf8` Arrow type

^3^: Only lists where all elements are the same type are able to be translated 
to Arrow list type (which is a "list of" some type).


## Arrow to R

| Arrow type        | R type                       |
|-------------------|------------------------------|
| boolean           | logical                      |
| int8              | integer                      |
| int16             | integer                      |
| int32             | integer                      |
| int64             | integer^1^                   |
| uint8             | integer                      |
| uint16            | integer                      |
| uint32            | integer^1^                   |
| uint64            | integer^1^                   |
| float16           | -^2^                         |
| float32           | double                       |
| float64           | double                       |
| utf8              | character                    |
| large_utf8        | character                    |
| binary            | arrow_binary ^3^             |
| large_binary      | arrow_large_binary ^3^       |
| fixed_size_binary | arrow_fixed_size_binary ^3^  |
| date32            | Date                         |
| date64            | POSIXct                      |
| time32            | hms::hms                     |
| time64            | hms::hms                     |
| timestamp         | POSIXct                      |
| duration          | difftime                     |
| decimal           | double                       |
| dictionary        | factor^4^                    |
| list              | arrow_list ^5^               |
| large_list        | arrow_large_list ^5^         |
| fixed_size_list   | arrow_fixed_size_list ^5^    |
| struct            | data.frame                   |
| null              | vctrs::vctrs_unspecified     |
| map               | arrow_list ^5^               |
| union             | -^2^                         |

^1^: These integer types may contain values that exceed the range of R's 
`integer` type (32-bit signed integer). When they do, `uint32` and `uint64` are 
converted to `double` ("numeric") and `int64` is converted to 
`bit64::integer64`. This conversion can be disabled (so that `int64` always
yields a `bit64::integer64` vector) by setting `options(arrow.int64_downcast = FALSE)`.

^2^: Some Arrow data types do not currently have an R equivalent and will raise an error
if cast to or mapped to via a schema.

^3^: `arrow*_binary` classes are implemented as lists of raw vectors. 

^4^: Due to the limitation of R factors, Arrow `dictionary` values are coerced
to string when translated to R if they are not already strings.

^5^: `arrow*_list` classes are implemented as subclasses of `vctrs_list_of` 
with a `ptype` attribute set to what an empty Array of the value type converts to. 


## R object attributes

Arrow supports custom key-value metadata attached to Schemas. When we convert a `data.frame` to an Arrow Table or RecordBatch, the package stores any `attributes()` attached to the columns of the `data.frame` in the Arrow object's Schema. These attributes are stored under the "r" key; you can assign additional string metadata under any other key you wish, like `x$metadata$new_key <- "new value"`.

This metadata is preserved when writing the table to Feather or Parquet, and when reading those files into R, or when calling `as.data.frame()` on a Table/RecordBatch, the column attributes are restored to the columns of the resulting `data.frame`. This means that custom data types, including `haven::labelled`, `vctrs` annotations, and others, are preserved when doing a round-trip through Arrow.

Note that the `attributes()` stored in `$metadata$r` are only understood by R. If you write a `data.frame` with `haven` columns to a Feather file and read that in Pandas, the `haven` metadata won't be recognized there. (Similarly, Pandas writes its own custom metadata, which the R package does not consume.) You are free, however, to define custom metadata conventions for your application and assign any (string) values you want to other metadata keys. For more details, see the documentation for `schema()`.

