---
title: "Installing development versions"
description: >
  Learn how to install nightly builds of `arrow` 
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installing development versions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Users of the `arrow` package will typically want to use the latest release version of the package, but may occasionally require a development build. Arrow developers are more likely to need the current development version. In this vignette we describe the process for installing the development version.

## Install nightly builds

Development versions of the package (binary and source) are built
nightly and hosted at <https://nightlies.apache.org/arrow/r/>. 
These nightly package builds are not official Apache releases and are
not recommended for production use. They may be useful for testing bug
fixes and new features under active development.

To install `arrow` from there, use the following command:

``` r
install.packages("arrow", repos = c(arrow = "https://nightlies.apache.org/arrow/r", getOption("repos")))
```

Conda users can install `arrow` nightly builds with:

``` shell
conda install -c arrow-nightlies -c conda-forge --strict-channel-priority r-arrow
```

If you already have a version of `arrow` installed, you can switch to
the latest nightly development version as follows:

``` r
arrow::install_arrow(nightly = TRUE)
```

## Install from git repo

An alternative way to obtain a development versions is to install the R package from a git checkout. To do so, type the following at the terminal:

```shell
git clone https://github.com/apache/arrow
cd arrow/r
R CMD INSTALL .
```

If you don't already have libarrow on your system,
when installing the R package from source, it will also download and build
libarrow for you. See the section above on build environment
variables for options for configuring the build source and enabled features.

## Further reading

- For users looking for information about installing on Linux, see `vignette("install_linux", package = "arrow")`.
- For developers looking to understand the installation scripts, see `vignette("install_details", package = "arrow")`.



