load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "double-conversion",
    build_file = "//bazel:double_conversion.BUILD",
    sha256 = "a63ecb93182134ba4293fd5f22d6e08ca417caafa244afaa751cbfddf6415b13",
    strip_prefix = "double-conversion-3.1.5",
    urls = ["https://github.com/google/double-conversion/archive/v3.1.5.tar.gz"],
)

http_archive(
    name = "googletest",
    sha256 = "9dc9157a9a1551ec7a7e43daea9a694a0bb5fb8bec81235d8a1e6ef64c716dcb",
    strip_prefix = "googletest-release-1.10.0",
    urls = ["https://github.com/google/googletest/archive/release-1.10.0.tar.gz"],
)

http_archive(
    name = "rapidjson",
    build_file = "//bazel:rapidjson.BUILD",
    sha256 = "de623a7577defec15b55f82813a05a6f0fe60e337ffa8a5ee4b2c13bd8417028",
    strip_prefix = "rapidjson-2bbd33b33217ff4a73434ebf10cdac41e2ef5e34/include",
    urls = ["https://github.com/miloyip/rapidjson/archive/2bbd33b33217ff4a73434ebf10cdac41e2ef5e34.tar.gz"],
)

new_local_repository(
    name = "flatbuffers",
    build_file = "//bazel:flatbuffers.BUILD",
    path = "../thirdparty/flatbuffers/include",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

all_content = """
package(default_visibility = ["//visibility:public"])
filegroup(name = "all", srcs = glob(["**"]))

cc_library(name = "boost_headers", hdrs = glob(["**/*.hpp"]),
includes = ["."]
   )
"""

http_archive(
    name = "rules_foreign_cc",
    sha256 = "bdfc2734367a1242514251c7ed2dd12f65dd6d19a97e6a2c61106851be8e7fb8",
    strip_prefix = "rules_foreign_cc-master",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

http_archive(
    name = "boost",
    build_file_content = all_content,
    sha256 = "da3411ea45622579d419bfda66f45cd0f8c32a181d84adfa936f5688388995cf",
    strip_prefix = "boost_1_68_0",
    urls = ["https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"],
)
