# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ArrayBuilder <- function(xptr_type) {
    .Call(`_rrrow_ArrayBuilder`, xptr_type)
}

ArrayBuilder__num_children <- function(xptr_type) {
    .Call(`_rrrow_ArrayBuilder__num_children`, xptr_type)
}

#' @export
field <- function(name, type, nullable = TRUE) {
    .Call(`_rrrow_field`, name, type, nullable)
}

bla <- function() {
    .Call(`_rrrow_bla`)
}

#' @export
int8 <- function() {
    .Call(`_rrrow_int8`)
}

#' @export
int16 <- function() {
    .Call(`_rrrow_int16`)
}

#' @export
int32 <- function() {
    .Call(`_rrrow_int32`)
}

#' @export
int64 <- function() {
    .Call(`_rrrow_int64`)
}

#' @export
uint8 <- function() {
    .Call(`_rrrow_uint8`)
}

#' @export
uint16 <- function() {
    .Call(`_rrrow_uint16`)
}

#' @export
uint32 <- function() {
    .Call(`_rrrow_uint32`)
}

#' @export
uint64 <- function() {
    .Call(`_rrrow_uint64`)
}

#' @export
float16 <- function() {
    .Call(`_rrrow_float16`)
}

#' @export
float32 <- function() {
    .Call(`_rrrow_float32`)
}

#' @export
float64 <- function() {
    .Call(`_rrrow_float64`)
}

#' @export
boolean <- function() {
    .Call(`_rrrow_boolean`)
}

#' @export
utf8 <- function() {
    .Call(`_rrrow_utf8`)
}

#' @export
date32 <- function() {
    .Call(`_rrrow_date32`)
}

#' @export
date64 <- function() {
    .Call(`_rrrow_date64`)
}

#' @export
null <- function() {
    .Call(`_rrrow_null`)
}

#' @export
decimal_type <- function(precision, scale) {
    .Call(`_rrrow_decimal_type`, precision, scale)
}

#' @export
fixed_size_binary <- function(byte_width) {
    .Call(`_rrrow_fixed_size_binary`, byte_width)
}

timestamp1 <- function(unit) {
    .Call(`_rrrow_timestamp1`, unit)
}

timestamp2 <- function(unit, timezone) {
    .Call(`_rrrow_timestamp2`, unit, timezone)
}

#' @export
time32 <- function(unit) {
    .Call(`_rrrow_time32_`, unit)
}

#' @export
time64 <- function(unit) {
    .Call(`_rrrow_time64_`, unit)
}

#' @export
list_ <- function(x) {
    .Call(`_rrrow_list_`, x)
}

#' @export
struct_ <- function(fields) {
    .Call(`_rrrow_struct_`, fields)
}

DataType_ToString <- function(type) {
    .Call(`_rrrow_DataType_ToString`, type)
}

schema_ <- function(fields) {
    .Call(`_rrrow_schema_`, fields)
}

Schema_ToString <- function(type) {
    .Call(`_rrrow_Schema_ToString`, type)
}

