package(default_visibility = ["//arrow/python:__pkg__"])

cc_library(
  name = "test_main",
  srcs = ["test_main.cc"],
  deps = ["//arrow/python:platform",
          "//arrow/python:datetime",
          "//arrow/python:init",
          "@googletest//:gtest"])

