// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatbuf

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Same as List, but with 64-bit offsets, allowing to represent
/// extremely large data values.
type LargeList struct {
	_tab flatbuffers.Table
}

func GetRootAsLargeList(buf []byte, offset flatbuffers.UOffsetT) *LargeList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LargeList{}
	x.Init(buf, n+offset)
	return x
}

func FinishLargeListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLargeList(buf []byte, offset flatbuffers.UOffsetT) *LargeList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LargeList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLargeListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LargeList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LargeList) Table() flatbuffers.Table {
	return rcv._tab
}

func LargeListStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LargeListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
