# Ruby lint begins minimal.
# All of checkings changed to disable by default.
AllCops:
  DisabledByDefault: true

Lint:
  Enabled: false

# The recommendation width are 80 characters.
# Due to some codes over the limitation(80 characters),
# apply the relax value.
Layout/LineLength:
  Max: 100

Layout/ArgumentAlignment:
  Enabled: true
