aws_crt_cpp:
- 0.23.1
aws_sdk_cpp:
- 1.11.156
bzip2:
- '1'
c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos6
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler:
- None
cuda_compiler_version:
- None
cuda_compiler_version_min:
- '11.2'
cxx_compiler:
- gxx
cxx_compiler_version:
- '12'
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
gflags:
- '2.2'
glog:
- '0.6'
google_cloud_cpp:
- '2.12'
libabseil:
- '20230802'
libgrpc:
- '1.57'
libprotobuf:
- 4.23.4
lz4_c:
- 1.9.3
numpy:
- '1.22'
- '1.23'
- '1.22'
- '1.22'
openssl:
- '3'
orc:
- 1.9.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.10.* *_cpython
- 3.11.* *_cpython
- 3.8.* *_cpython
- 3.9.* *_cpython
re2:
- 2023.03.02
snappy:
- '1'
target_platform:
- linux-64
thrift_cpp:
- 0.19.0
ucx:
- 1.14.0
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
  - cuda_compiler
  - cuda_compiler_version
  - cdt_name
  - docker_image
- - libgrpc
  - libprotobuf
- - python
  - numpy
zlib:
- '1.2'
zstd:
- '1.5'
