aws_crt_cpp:
- 0.26.10
aws_sdk_cpp:
- 1.11.329
bzip2:
- '1'
c_compiler:
- vs2019
c_stdlib:
- vs
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler:
- None
cuda_compiler_version:
- None
cuda_compiler_version_min:
- '11.8'
cxx_compiler:
- vs2019
gflags:
- '2.2'
glog:
- '0.7'
libabseil:
- '20240116'
libcrc32c:
- '1.1'
libcurl:
- '8'
libgoogle_cloud_devel:
- '2.24'
libgoogle_cloud_storage_devel:
- '2.24'
libgrpc:
- '1.62'
libprotobuf:
- 4.25.3
lz4_c:
- 1.9.3
openssl:
- '3'
orc:
- 2.0.1
re2:
- 2023.09.01
snappy:
- '1.2'
target_platform:
- win-64
thrift_cpp:
- 0.19.0
zip_keys:
- - cuda_compiler
  - cuda_compiler_version
zlib:
- '1'
zstd:
- '1.5'
