# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[lint]
select = [
  "B",   # flake8-bugbear
  "BLE", # flake8-blind-except
  "C4",  # comprehensions
  "D",   # pydocstyle
  "E",   # pycodestyle
  "EXE", # flake8-executable
  "F",   # pyflakes
  "FA",  # flake8-future-annotations
  "G",   # flake8-logging-format
  "FLY", # flynt (format string conversion)
  "I",   # isort
  "ICN", # flake8-import-conventions
  "INP", # flake8-no-pep420 (implicit namespace packages)
  "ISC", # flake8-implicit-str-concat
  "PGH", # pygrep-hooks
  "PIE", # flake8-pie
  "PL",  # pylint
  "RET", # flake8-return
  "RUF", # ruff-specific rules
  "SIM", # flake8-simplify
  "T10", # flake8-debugger
  "T20", # flake8-print
  "TCH", # flake8-type-checking
  "TID", # flake8-tidy-imports
  "UP",  # pyupgrade
  "W",   # pycodestyle
  "YTT", # flake8-2020
  "S",   # flake8-bandit
]
ignore = [
#   "B028",    # required stacklevel argument to warn
  "B017",    # `pytest.raises(Exception)` should be considered evil
  "B027",    # `CDataExporter.run_gc` is an empty method in an abstract base class, but has no abstract decorator
  "B904",    # raise from e or raise from None in exception handlers
  "BLE001",  # Do not catch blind exception: `Exception`
#   "B905",    # zip-without-explicit-strict
  "C408",   # Unnecessary `dict()` call (rewrite as a literal)
#   "C408",    # dict(...) as literal
  "D100",    # public module
  "D101",    # public class
  "D102",    # public method
  "D103",    # public function
  "D104",    # public package
  "D105",    # magic methods
  "D106",    # nested class
  "D107",    # init
  "D200",    # One-line docstring should fit on one line
#   "D202",    # blank lines after function docstring
  "D203",    # blank line before class docstring
  "D205",    # 1 blank line required between summary line and description
  "D210",    # No whitespaces allowed surrounding docstring text
  "D213",    # Multi-line docstring summary should start at the second line
  "D301",    # Use `r"""` if any backslashes in a docstring
  "D400",    # First line should end with a period
  "D401",    # Imperative mood
#   "D402",    # First line should not be the function's signature
  "D413",    # Blank line required after last section
  "D415",    # First line should end with a period, question mark, or exclamation point
  "D417",    # Missing argument descriptions in the docstring
  "FLY002",  # Consider `f"{}.{}"` instead of string join"
#   "E501",    # line-too-long, this is automatically enforced by ruff format
#   "E731",    # lambda-assignment
  "ICN001",  # `xml.etree.ElementTree` should be imported as `ET`
  "INP001",  # implicit-namespace-package
  "ISC001",  # single line implicit string concat, handled by ruff format
  "G004",    # Logging statement uses f-string
#   "PGH003",  # blanket-type-ignore
#   "PLC0105", # covariant type parameters should have a _co suffix
#   "PLR0124", # name compared with self, e.g., a == a
#   "PLR0911", # too many return statements
  "PLR0912", # too many branches
  "PLR0913", # too many arguments
  "PLR0915", # too many statements
  "PLR2004", # forces everything to be a constant
  "PLW2901", # overwriting loop variable
  "RET503",  # Missing explicit `return` at the end of function able to return non-`None` value
  "RET504",  # unnecessary-assign, these are useful for debugging
  "RET505",  # superfluous-else-return, stylistic choice
  "RET506",  # superfluous-else-raise, stylistic choice
  "RET507",  # superfluous-else-continue, stylistic choice
  "RET508",  # superfluous-else-break, stylistic choice
  "RUF005",  # splat instead of concat
  "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
#   "SIM102",  # nested ifs
  "SIM108",  # convert everything to ternary operator
#   "SIM114",  # combine `if` branches using logical `or` operator
#   "SIM116",  # dictionary instead of `if` statements
  "SIM117",  # Use a single `with` statement with multiple contexts instead of nested `with` statements
#   "SIM118",  # remove .keys() calls from dictionaries
#   "SIM300",  # yoda conditions
  "UP006",   # Use `list` instead of `List` for type annotation
  "UP007",   # Optional[str] -> str | None
  "UP035",   # `typing.List` is deprecated, use `list` instead
#   "UP038",   # non-pep604-isinstance, results in slower code
  "PLW1510", # `subprocess.run` without explicit `check` argument
  "S101",    # ignore "Use of `assert` detected"
  "S310",    # Audit URL open for permitted schemes. Allowing use of `file:` or custom schemes is often unexpected.
  "S603",    # `subprocess` call: check for execution of untrusted input
  "S607",    # Starting a process with a partial executable path
  "S701",    # By default, jinja2 sets `autoescape` to `False`. Consider using `autoescape=True` or the `select_autoescape` function to mitigate XSS vulnerabilities.
  "S113",    # Probable use of `requests` call without timeout
  "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
  "T201",    # `print` found
  "TID252"   # Prefer absolute imports over relative imports from parent modules
]
# none of these codes will be automatically fixed by ruff
unfixable = [
  "T201",   # print statements
  "F401",   # unused imports
  "RUF100", # unused noqa comments
  "F841",   # unused variables
]

[lint.isort]
required-imports = ["from __future__ import annotations"]

[format]
docstring-code-format = true
docstring-code-line-length = 88