build: false

os: Visual Studio 2015

platform:
  - x86
  - x64

environment:
  global:
    MINICONDA: C:\xsimd-conda
  matrix:
    - JOB: "SSE2"
      CXXFLAGS: ""
      VCVARSALL: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
      RUNTEST: ".\\test_xsimd"
    - JOB: "AVX2"
      CXXFLAGS: "/arch:AVX2"
      VCVARSALL: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
      RUNTEST: ".\\test_xsimd"
    - JOB: "AVX512"
      CXXFLAGS: "/arch:AVX512"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARSALL: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
      RUNTEST: "ECHO"

init:
  - "ECHO %MINICONDA%"
  - call "%VCVARSALL%" %PLATFORM%
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\xsimd-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install cmake xtl -c conda-forge
  - ps: if($env:Platform -eq "x64"){$env:EnableXTL=1} else {$env:EnableXTL=0}
  - cmake -G "NMake Makefiles" -D DOWNLOAD_GTEST=1 -D ENABLE_XTL_COMPLEX=%EnableXTL% -D CMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -D CMAKE_BUILD_TYPE=Release .
  - nmake test_xsimd
  - cd test

build_script:
  - "%RUNTEST%"
