load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "rapidjson_defs",
    hdrs = ["rapidjson_defs.h"],
    deps = ["//cpp/src/arrow/util:sse_util"],
)

