package(default_visibility = ["//visibility:public"])
load("//bazel:arrow_cc_library.bzl", "arrow_cc_library")
arrow_cc_library(
    name = "public_api",
    hdrs = ["api.h", "filesystem.h", "localfs.h", "mockfs.h", "s3fs.h"],
)

