// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatbuf

import "strconv"

type CompressionType int8

const (
	CompressionTypeLZ4_FRAME CompressionType = 0
	CompressionTypeZSTD      CompressionType = 1
)

var EnumNamesCompressionType = map[CompressionType]string{
	CompressionTypeLZ4_FRAME: "LZ4_FRAME",
	CompressionTypeZSTD:      "ZSTD",
}

var EnumValuesCompressionType = map[string]CompressionType{
	"LZ4_FRAME": CompressionTypeLZ4_FRAME,
	"ZSTD":      CompressionTypeZSTD,
}

func (v CompressionType) String() string {
	if s, ok := EnumNamesCompressionType[v]; ok {
		return s
	}
	return "CompressionType(" + strconv.FormatInt(int64(v), 10) + ")"
}
