# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'
services:

  pg:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}

  graphile:
    image: graphile/postgraphile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - pg
    command:
      - --connection
      - postgres://${PG_USER}:${PG_PASS}@pg:5432/${PG_USER}
      - --schema
      - public
      - --watch
