name: 'Install Python'
inputs:
  python-version:
    required: true
    default: '3.9'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
      working-directory: ${{env.working-directory}}
