// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

type TypeMetadata = byte
const (
	TypeMetadataNONE TypeMetadata = 0
	TypeMetadataCategoryMetadata TypeMetadata = 1
	TypeMetadataTimestampMetadata TypeMetadata = 2
	TypeMetadataDateMetadata TypeMetadata = 3
	TypeMetadataTimeMetadata TypeMetadata = 4
)

var EnumNamesTypeMetadata = map[TypeMetadata]string{
	TypeMetadataNONE:"NONE",
	TypeMetadataCategoryMetadata:"CategoryMetadata",
	TypeMetadataTimestampMetadata:"TimestampMetadata",
	TypeMetadataDateMetadata:"DateMetadata",
	TypeMetadataTimeMetadata:"TimeMetadata",
}

