versions:
  "19.0.1":
    folder: all
  "18.1.0":
    folder: all
  "18.0.0":
    folder: all
  "17.0.0":
    folder: all
  "16.1.0":
    folder: all
  "15.0.0":
    folder: all
  "14.0.2":
    folder: all