# This file was generated by stubgen-pyx v0.2.23 from python/pyarrow/_pyarrow_cpp_tests.pyx

from typing import Callable

from _typeshed import Incomplete
from pyarrow.includes.common import *
from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow import CStatus
from typing_extensions import TypeAlias

cb_test_func: TypeAlias = Callable[[], CStatus]
CTestCase: TypeAlias = Incomplete

class CppTestCase:
    """
    A simple wrapper for a C++ test case.
    """
    @property
    def name(self): ...
    def __repr__(self): ...
    def __call__(self): ...

def get_cpp_tests():
    """
    Get a list of C++ test cases.
    """
