# This file was generated by stubgen-pyx v0.2.23 from python/pyarrow/_substrait.pyx

from pyarrow.includes.libarrow import *
from pyarrow.includes.libarrow_substrait import *
from pyarrow.lib import *


class SubstraitSchema:
    """A Schema encoded for Substrait usage.

    The SubstraitSchema contains a schema represented
    both as a substrait ``NamedStruct`` and as an
    ``ExtendedExpression``.

    The ``ExtendedExpression`` is available for cases where types
    used by the schema require extensions to decode them.
    In such case the schema will be the ``base_schema`` of the
    ``ExtendedExpression`` and all extensions will be provided.
    """
    def __init__(self, schema, expression): ...
    def to_pysubstrait(self):
        """Convert the schema to a substrait-python ExtendedExpression object."""

class BoundExpressions(_Weakrefable):
    """
    A collection of named expressions and the schema they are bound to

    This is equivalent to the Substrait ExtendedExpression message
    """
    def __init__(self): ...
    @property
    def schema(self):
        """
        The common schema that all expressions are bound to
        """
    @property
    def expressions(self):
        """
        A dict from expression name to expression
        """
    @classmethod
    def from_substrait(cls, message):
        """
        Convert a Substrait message into a BoundExpressions object

        Parameters
        ----------
        message : Buffer or bytes or protobuf Message
            The message to convert to a BoundExpressions object

        Returns
        -------
        BoundExpressions
            The converted expressions, their names, and the bound schema
        """

def run_query(plan, *, table_provider=None, use_threads=True):
    """
    Execute a Substrait plan and read the results as a RecordBatchReader.

    Parameters
    ----------
    plan : Union[Buffer, bytes]
        The serialized Substrait plan to execute.
    table_provider : object (optional)
        A function to resolve any NamedTable relation to a table.
        The function will receive two arguments which will be a list
        of strings representing the table name and a pyarrow.Schema representing
        the expected schema and should return a pyarrow.Table.
    use_threads : bool, default True
        If True then multiple threads will be used to run the query.  If False then
        all CPU intensive work will be done on the calling thread.

    Returns
    -------
    RecordBatchReader
        A reader containing the result of the executed query

    Examples
    --------
    >>> import pyarrow as pa
    >>> from pyarrow.lib import tobytes
    >>> import pyarrow.substrait as substrait
    >>> test_table_1 = pa.Table.from_pydict({"x": [1, 2, 3]})
    >>> test_table_2 = pa.Table.from_pydict({"x": [4, 5, 6]})
    >>> def table_provider(names, schema):
    ...     if not names:
    ...        raise Exception("No names provided")
    ...     elif names[0] == "t1":
    ...        return test_table_1
    ...     elif names[1] == "t2":
    ...        return test_table_2
    ...     else:
    ...        raise Exception("Unrecognized table name")
    ...
    >>> substrait_query = '''
    ...         {
    ...             "relations": [
    ...             {"rel": {
    ...                 "read": {
    ...                 "base_schema": {
    ...                     "struct": {
    ...                     "types": [
    ...                                 {"i64": {}}
    ...                             ]
    ...                     },
    ...                     "names": [
    ...                             "x"
    ...                             ]
    ...                 },
    ...                 "namedTable": {
    ...                         "names": ["t1"]
    ...                 }
    ...                 }
    ...             }}
    ...             ]
    ...         }
    ... '''
    >>> buf = pa._substrait._parse_json_plan(tobytes(substrait_query))
    >>> reader = pa.substrait.run_query(buf, table_provider=table_provider)
    >>> reader.read_all()
    pyarrow.Table
    x: int64
    ----
    x: [[1,2,3]]
    """
def serialize_schema(schema):
    """
    Serialize a schema into a SubstraitSchema object.

    Parameters
    ----------
    schema : Schema
        The schema to serialize

    Returns
    -------
    SubstraitSchema
        The schema stored in a SubstraitSchema object.
    """
def deserialize_schema(buf):
    """
    Deserialize a ``NamedStruct`` Substrait message
    or a SubstraitSchema object into an Arrow Schema object

    Parameters
    ----------
    buf : Buffer or bytes or SubstraitSchema
        The message to deserialize

    Returns
    -------
    Schema
        The deserialized schema
    """
def serialize_expressions(exprs, names, schema, *, allow_arrow_extensions=False):
    """
    Serialize a collection of expressions into Substrait

    Substrait expressions must be bound to a schema.  For example,
    the Substrait expression ``a:i32 + b:i32`` is different from the
    Substrait expression ``a:i64 + b:i64``.  Pyarrow expressions are
    typically unbound.  For example, both of the above expressions
    would be represented as ``a + b`` in pyarrow.

    This means a schema must be provided when serializing an expression.
    It also means that the serialization may fail if a matching function
    call cannot be found for the expression.

    Parameters
    ----------
    exprs : list of Expression
        The expressions to serialize
    names : list of str
        Names for the expressions
    schema : Schema
        The schema the expressions will be bound to
    allow_arrow_extensions : bool, default False
        If False then only functions that are part of the core Substrait function
        definitions will be allowed.  Set this to True to allow pyarrow-specific functions
        and user defined functions but the result may not be accepted by other
        compute libraries.

    Returns
    -------
    Buffer
        An ExtendedExpression message containing the serialized expressions
    """
def deserialize_expressions(buf):
    """
    Deserialize an ExtendedExpression Substrait message into a BoundExpressions object

    Parameters
    ----------
    buf : Buffer or bytes
        The message to deserialize

    Returns
    -------
    BoundExpressions
        The deserialized expressions, their names, and the bound schema
    """
def get_supported_functions():
    """
    Get a list of Substrait functions that the underlying
    engine currently supports.

    Returns
    -------
    list[str]
        A list of function ids encoded as '{uri}#{name}'
    """
