name: License check

on: pull_request

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check License Header
      uses: enarx/spdx@master
      with: 
        licenses: Apache-2.0 MIT 