#!/bin/python

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This script is modified from its original version in GitHub. Original source:
# https://github.com/lemire/FrameOfReference/blob/146948b6058a976bc7767262ad3a2ce201486b93/scripts/turbopacking64.py

# Usage:
#   python bpacking64_codegen.py > bpacking64_default_internal.h


import dataclasses
import sys


LICENSE = """// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// This file was generated by script which is modified from its original version in GitHub.
// Original source:
// https://github.com/lemire/FrameOfReference/blob/master/scripts/turbopacking64.py
// The original copyright notice follows.

// This code is released under the
// Apache License Version 2.0 http://www.apache.org/licenses/.
// (c) Daniel Lemire 2013
"""

HEADER = """
#pragma once

#include <cstdint>
#include <cstring>

#include "arrow/util/endian.h"
#include "arrow/util/ubsan.h"

namespace arrow::internal {
"""

FOOTER = """
}  // namespace arrow::internal
"""


@dataclasses.dataclass
class ScalarUnpackGenerator:
    out_bit_width: int
    smart_halve: bool

    @property
    def out_byte_width(self) -> int:
        return self.out_bit_width // 8

    @property
    def unsigned_type(self) -> str:
        return f"uint{self.out_bit_width}_t"

    @property
    def unsigned_type_half(self) -> str:
        return f"uint{self.out_bit_width // 2}_t"

    @property
    def howmany(self) -> int:
        """How many values are we going to pack?"""
        if self.smart_halve:
            return self.out_bit_width // 2
        return self.out_bit_width

    def howmanywords(self, bit: int) -> int:
        return (self.howmany * bit + self.out_bit_width - 1) // self.out_bit_width

    def howmanybytes(self, bit: int) -> int:
        return (self.howmany * bit + self.out_byte_width - 1) // self.out_byte_width

    def unpack_signature(self, bit: int) -> str:
        return (
            f"inline const uint8_t* unpack{bit}_{self.out_bit_width}"
            f"(const uint8_t* in, {self.unsigned_type}* out)"
            "{"
        )

    def print_unpack_0(self) -> None:
        print(self.unpack_signature(0))
        print(f"  std::memset(out, 0, {self.howmany} * {self.out_byte_width});")
        print("  return in;")
        print("}")

    def print_unpack_last(self) -> None:
        print(self.unpack_signature(self.out_bit_width))
        print(f"  for(int k = 0; k < {self.howmany}; k += 1) {{")
        print(f"    auto w = util::SafeLoadAs<{self.unsigned_type}>(in);")
        print("    out[k] = bit_util::FromLittleEndian(w);")
        print(f"    in += {self.out_byte_width};")
        print("  }")
        print("  return in;")
        print("}")

    def print_unpack_k(self, bit: int) -> None:
        print(self.unpack_signature(bit))
        print(
            f"  constexpr {self.unsigned_type} mask = "
            f"(({self.unsigned_type}{{1}} << {bit}) - {self.unsigned_type}{{1}});"
        )
        print("")
        maskstr = " & mask"

        for k in range(self.howmanywords(bit) - 1):
            print(
                f"  const auto w{k} = "
                f"bit_util::FromLittleEndian(util::SafeLoadAs<{self.unsigned_type}>(in));"
            )
            print(f"  in += {self.out_byte_width};")

        k = self.howmanywords(bit) - 1
        if self.smart_halve and bit % 2 == 1:
            print(
                f"  auto w{k} = static_cast<{self.unsigned_type}>(util::SafeLoadAs<{self.unsigned_type_half}>(in));"
            )
            print(f"  w{k} = bit_util::FromLittleEndian(w{k});")
            print(f"  in += {self.out_byte_width // 2};")
        else:
            print(
                f"  const auto w{k} = "
                f"bit_util::FromLittleEndian(util::SafeLoadAs<{self.unsigned_type}>(in));"
            )
            print(f"  in += {self.out_byte_width};")

        for j in range(self.howmany):
            firstword = j * bit // self.out_bit_width
            secondword = (j * bit + bit - 1) // self.out_bit_width
            firstshift = (j * bit) % self.out_bit_width
            firstshiftstr = f" >> {firstshift}"
            if firstshift == 0:
                firstshiftstr = ""  # no need
            if firstword == secondword:
                if firstshift + bit == self.out_bit_width:
                    print(f"  out[{j}] = w{firstword}{firstshiftstr};")
                else:
                    print(f"  out[{j}] = (w{firstword}{firstshiftstr}){maskstr};")
            else:
                secondshift = self.out_bit_width - firstshift
                print(
                    f"  out[{j}] = ((w{firstword}{firstshiftstr}) | "
                    f"(w{firstword + 1} << {secondshift})){maskstr};"
                )
        print("")
        print("  return in;")
        print("}")

    def print_all(self) -> None:
        self.print_unpack_0()
        print("")

        for bit in range(1, self.out_bit_width):
            self.print_unpack_k(bit)
            print("")

        self.print_unpack_last()


if __name__ == "__main__":
    print(LICENSE)
    print("// WARNING: this file is generated, DO NOT EDIT.")
    print("// Usage:")
    print(f"//   python {' '.join(sys.orig_argv[1:])}")
    print(HEADER)

    ScalarUnpackGenerator(32, smart_halve=False).print_all()
    print("")

    ScalarUnpackGenerator(64, smart_halve=True).print_all()

    print(FOOTER)
