// Code generated by type.go.tmpl.
// DO NOT EDIT.

package math

import (
	"github.com/apache/arrow/go/arrow/array"
)

type Int64Funcs struct {
	sum func(a *array.Int64) int64
}

var (
	Int64 Int64Funcs
)

// Sum returns the summation of all elements in a.
func (f Int64Funcs) Sum(a *array.Int64) int64 {
	return f.sum(a)
}

func sum_int64_go(a *array.Int64) int64 {
	acc := int64(0)
	for _, v := range a.Int64Values() {
		acc += v
	}
	return acc
}
