#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

odbc_install_script="/Library/ODBC/arrow-odbc/lib/install_odbc.sh"
dsn_install_script="/Library/ODBC/arrow-odbc/lib/install_odbc_ini.sh"
driver_lib="/Library/ODBC/arrow-odbc/lib/libarrow_flight_sql_odbc.dylib"
dsn_file="/Library/ODBC/odbc.ini"

if [[ ! -x "$odbc_install_script" ]]; then
  echo "ERROR: ODBC install script $odbc_install_script not found" >&2
  exit 1
fi

"$odbc_install_script" "$driver_lib" || {
  echo "ERROR: Failed to register ODBC driver ($driver_lib)" >&2
  exit 1
}

if [[ ! -x "$dsn_install_script" ]]; then
  echo "ERROR: DSN install script $dsn_install_script not found" >&2
  exit 1
fi

"$dsn_install_script" "$dsn_file" || {
  echo "ERROR: Failed to register DSN to ($dsn_file)" >&2
  exit 1
}

# clean temporary script
rm -f "$odbc_install_script" "$dsn_install_script"
