# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: C GLib & Ruby

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
    tags:
      - '**'
    paths:
      - '.dockerignore'
      - '.github/workflows/ruby.yml'
      - 'ci/docker/**'
      - 'ci/scripts/c_glib_*'
      - 'ci/scripts/ccache_setup.sh'
      - 'ci/scripts/cpp_*'
      - 'ci/scripts/msys2_*'
      - 'ci/scripts/ruby_*'
      - 'ci/scripts/util_*'
      - 'c_glib/**'
      - 'cpp/**'
      - 'compose.yaml'
      - 'ruby/**'
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/workflows/ruby.yml'
      - 'ci/docker/**'
      - 'ci/scripts/c_glib_*'
      - 'ci/scripts/ccache_setup.sh'
      - 'ci/scripts/cpp_*'
      - 'ci/scripts/msys2_*'
      - 'ci/scripts/ruby_*'
      - 'ci/scripts/util_*'
      - 'c_glib/**'
      - 'cpp/**'
      - 'compose.yaml'
      - 'ruby/**'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

env:
  ARCHERY_DEBUG: 1
  DOCKER_VOLUME_PREFIX: ".docker/"

jobs:

  macos:
    name: ARM64 macOS GLib & Ruby
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    timeout-minutes: 60
    env:
      ARROW_BUILD_STATIC: OFF
      ARROW_BUILD_TESTS: OFF
      ARROW_BUILD_UTILITIES: OFF
      ARROW_DATASET: ON
      ARROW_FLIGHT: ON
      ARROW_FLIGHT_SQL: ON
      ARROW_GANDIVA: ON
      ARROW_GCS: ON
      ARROW_GLIB_GTK_DOC: true
      ARROW_GLIB_WERROR: true
      ARROW_HOME: /tmp/local
      ARROW_JEMALLOC: OFF
      ARROW_ORC: OFF
      ARROW_PARQUET: ON
      ARROW_WITH_BROTLI: ON
      ARROW_WITH_LZ4: ON
      ARROW_WITH_SNAPPY: ON
      ARROW_WITH_ZLIB: ON
      ARROW_WITH_ZSTD: ON
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive
      - name: Install Homebrew Dependencies
        shell: bash
        run: |
          # We can remove this once GitHub hosted runners include
          # Meson 1.8.4 or later by default.
          brew update
          brew bundle --file=cpp/Brewfile
          brew bundle --file=c_glib/Brewfile
          # For Meson.
          # See also: https://github.com/mesonbuild/meson/issues/7701
          echo "PKG_CONFIG=$(brew --prefix pkgconf)/bin/pkgconf" >> $GITHUB_ENV
      - name: Install Ruby Dependencies
        run: |
          export MAKEFLAGS="-j$(sysctl -n hw.ncpu)"
          bundle install --gemfile c_glib/Gemfile
          bundle install --gemfile ruby/Gemfile
          for ruby_package_gemfile in ruby/*/Gemfile; do \
            bundle install --gemfile ${ruby_package_gemfile}
          done
      - name: Setup ccache
        run: |
          ci/scripts/ccache_setup.sh
      - name: ccache info
        id: ccache-info
        shell: bash
        run: echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
      - name: Restore ccache
        uses: apache/infrastructure-actions/stash/restore@69afc125e535c4c41e7f1b7470f583087e0f344b
        with:
          path: ${{ steps.ccache-info.outputs.cache-dir }}
          key: ruby-ccache-macos
      - name: Build C++
        run: |
          ci/scripts/cpp_build.sh $(pwd) $(pwd)/build
      - name: Build GLib
        run: |
          ci/scripts/c_glib_build.sh $(pwd) $(pwd)/build
      - name: Save ccache
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: apache/infrastructure-actions/stash/save@69afc125e535c4c41e7f1b7470f583087e0f344b
        with:
          path: ${{ steps.ccache-info.outputs.cache-dir }}
          key: ruby-ccache-macos
      - name: Test GLib
        shell: bash
        run: ci/scripts/c_glib_test.sh $(pwd) $(pwd)/build
      - name: Test Ruby
        shell: bash
        run: ci/scripts/ruby_test.sh $(pwd) $(pwd)/build

