# -*- ruby -*-
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

require "pkg-config"
require "native-package-installer"

case RUBY_PLATFORM
when /mingw|mswin/
  task :default => "nothing"
else
  task :default => "dependency:check"
end

task :nothing do
end

namespace :dependency do
  desc "Check dependency"
  task :check do
    unless PKGConfig.check_version?("plasma-glib")
      unless NativePackageInstaller.install(:debian => "libplasma-glib-dev",
                                            :redhat => "plasma-glib-devel")
        exit(false)
      end
    end
  end
end
