%% Licensed to the Apache Software Foundation (ASF) under one
%% or more contributor license agreements.  See the NOTICE file
%% distributed with this work for additional information
%% regarding copyright ownership.  The ASF licenses this file
%% to you under the Apache License, Version 2.0 (the
%% "License"); you may not use this file except in compliance
%% with the License.  You may obtain a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.

%% To generate the diagram, use mermaid-cli
%% Example: docker run --rm -v $(pwd)/DissociatedIPC:/data minlag/mermaid-cli -i /data/SequenceDiagramSeparate.mmd

sequenceDiagram
  participant D as Data Stream
  participant C as Client
  participant M as Metadata Stream

  activate C
  C-->>+M: TAG: <want_data> BODY: <opaque ID>
  C-->>+D: TAG: <want_data> BODY: <opaque ID>
  M-->>C: MSG: [1] + <sequence number> + <schema metadata>
  loop each chunk
    par
      M-->>C: MSG: [1] + <sequence number> + <IPC metadata>
    and
      alt
        D-->>C: TAG: <inline data> | <sequence number> BODY: <raw body bytes>
      else
        D-->>C: TAG: <pointer list> | <sequence number> BODY: <pairs of uint64>
      end
    end
  end
  M-->>C: [0] + <sequence number>
  deactivate M
  loop
    C-->>D: TAG: <free_data> BODY: <list of uint64>
  end
  deactivate D
  deactivate C
