%% Licensed to the Apache Software Foundation (ASF) under one
%% or more contributor license agreements.  See the NOTICE file
%% distributed with this work for additional information
%% regarding copyright ownership.  The ASF licenses this file
%% to you under the Apache License, Version 2.0 (the
%% "License"); you may not use this file except in compliance
%% with the License.  You may obtain a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.

sequenceDiagram
  participant D as Data Stream
  participant C as Client
  participant M as Metadata Stream

  activate C
  C-->>+M: TaggedMessage(server.want_data, bytes=ID_of_desired_data)
  C-->>+D: TaggedMessage(server.want_data, bytes=ID_of_desired_data)
  M-->>C: Message(bytes([1]) + le_bytes(sequence_number) + schema_metadata)
  loop each batch
    par
      M-->>C: Message(bytes([1]) + le_bytes(sequence_number) + batch_metadata)
    and
      alt
        D-->>C: TaggedMessage((bytes[0] << 55) | le_bytes(sequence_number),<br/>bytes=batch_data)
      else
        D-->>C: TaggedMessage((bytes[1] << 55) | le_bytes(sequence_number),<br/>bytes=uint64_pairs)
      end
    end
  end
  M-->>C: Message(bytes([0]) + le_bytes(sequence_number))
  deactivate M
  loop
    C-->>D: TaggedMessage(server.free_data, bytes=uint64_list)
  end
  deactivate D
  deactivate C
