%% Licensed to the Apache Software Foundation (ASF) under one
%% or more contributor license agreements.  See the NOTICE file
%% distributed with this work for additional information
%% regarding copyright ownership.  The ASF licenses this file
%% to you under the Apache License, Version 2.0 (the
%% "License"); you may not use this file except in compliance
%% with the License.  You may obtain a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.

sequenceDiagram    
  participant C as Client
  participant S as Server
  activate C
  C-->>+S: TaggedMessage(server.want_data, bytes=ID_of_desired_data)
  S-->>C: Message(bytes([1]) + le_bytes(sequence_number) + schema_metadata)
  par
    loop each chunk
      S-->>C: Message(bytes([1]) + le_bytes(sequence_number) + batch_metadata)
    end
    S-->>C: Message(bytes([0]) + le_bytes(sequence_number))
  and
    loop each chunk
      alt
        S-->>C: TaggedMessage((bytes[0] << 55) | le_bytes(sequence_number),<br/>bytes=batch_data)
      else
        S-->>C: TaggedMessage((bytes[1] << 55) | le_bytes(sequence_number),<br/>bytes=uint64_pairs)
      end
    end
  end
  
  loop
    C-->>S: TaggedMessage(server.free_data, bytes=uint64_list)
  end
  deactivate S
  deactivate C
