jobs:
  - job: 'Linux_1'
    strategy:
      matrix:
        gcc_6_force_no_instr_set:
          gcc_version: '6'
          force_no_instr_set: 1
        gcc_6_enable_xtl_complex:
          gcc_version: '6'
          enable_xtl_complex: 1
        gcc_7_avx512:
          gcc_version: '7'
          avx512: 1
        gcc_8_aarch64:
          cross_compile: 1
          gcc_version: '8'
          arm_arch_dir: 'aarch64-linux-gnu'
          arm_arch_target: 'armv8-a'
        gcc_8:
          gcc_version: '8'
          enable_xtl_complex: 1
        gcc_9:
          gcc_version: '9'
        gcc_9_m32:
          gcc_version: '9'
          i686: 1
    pool:
      vmImage: ubuntu-18.04
    variables:
      CC: gcc-$(gcc_version)
      CXX: g++-$(gcc_version)
      cross_compile: 0
      avx: 0
      avx512: 0
      i686: 0
      enable_xtl_complex: 0
      force_no_instr_set: 0
    timeoutInMinutes: 30
    steps:

      - script: |
          if [[ $(gcc_version) == '6' || $(gcc_version) == '7' || $(gcc_version) == '8' ]]; then
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get --no-install-suggests --no-install-recommends install g++-$(gcc_version)
          fi
          if [[ $(cross_compile) == 1 ]]; then
            if [[ $(arm_arch_dir) == 'aarch64-linux-gnu' ]]; then
              sudo apt-get --no-install-suggests --no-install-recommends install g++-8-aarch64-linux-gnu gcc-8-aarch64-linux-gnu
              sudo apt-get --no-install-suggests --no-install-recommends install qemu qemu-system-aarch64
            fi
          fi
          if [[ $(i686) == 1 ]]; then
            sudo dpkg --add-architecture i386
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get --no-install-suggests --no-install-recommends install gcc-$(gcc_version)-multilib g++-$(gcc_version)-multilib linux-libc-dev:i386
          fi
        displayName: Install build toolchain

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
